name = "TuringModels"
uuid = "ead7e11d-4ba5-55c3-9d74-177ea73ef1fd"
authors = ["Rob Goedman, Richard Torkar, Rik Huijzer, Martin Trapp and contributors"]
version = "2.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
CSV = "0.8"
DataFrames = "0.22"
Distributions = "0.24"
Franklin = "0.10"
NodeJS = "1.1"
RData = "0.7"
StatsFuns = "0.9"
StatsPlots = "0.14"
Turing = "0.15"
julia = "1"
