name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Python is necessary for the pre-rendering (minification) step
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: julia-actions/setup-julia@v1
        with:
          version: 1 # Latest stable release, for example, `1.5.3`.

      - name: Build site
        run: julia -e '
          using Pkg; Pkg.add(["NodeJS", "Franklin"]);
          using NodeJS; run(`$(npm_cmd()) install highlight.js`);
          using Franklin;
          Pkg.dev(path="."); Pkg.activate("."); Pkg.instantiate();
          Franklin.optimize();
          verify_links()' > build.log

      - name: Deploy to secondary branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__site
